spring:

  # Additional dev-specific settings
  jpa:
    show-sql: true

# Development-specific logging configuration
logging:
  level:
    com.gucardev: debug
    org.hibernate.SQL: debug
#    org.springframework.web: debug
#    io.micrometer.prometheus: warn