spring:
  application:
    name: wallet-app-backend-spring-boot
  profiles:
    default: dev

  data:
    jdbc:
      dialect: mysql

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      envers:
        audit_table_suffix: _history

  messages:
    encoding: UTF-8
  docker:
    compose:
      enabled: false

# Actuator configuration for monitoring and management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    port: 8081
  tracing:
    sampling:
      probability: '1.0'

# Logging configuration
logging:
  level:
    root: info

# Caffeine cache configuration
cache:
  short:
    ttl: '60'
  default:
    max-size: '1000'
  medium:
    ttl: '120'

# Custom app constants
constants:
  api-url: url
  api-key: key
  default-auditor: SYSTEM

app:
  jwt.secret-key: '8e8901fe01244c7d70f6c9225422664bfa4209fb0b0d30a1400fc3069171ed63b935d9ca98d4146d9ab5fffccb76300d23d412f9d07ec7051bbd1ed4dc8b893f'
  jwt.validity-in-minutes: 60

encryption:
  secret: 'm1ZZ7ywf9N1aAZJpAW4uUg=='